
const data = {
    products: [
        {
            //_id: '1',
            name: 'Save Turtle shirt',
            slug: 'save-turtle-shirt',
            category: 'Shirts',
            image:'/images/t1.jpg', 
            price: 120,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high Quality T-shirt with the theme of Save Turtle',
        },
        {
            //_id: '2',
            name: 'Save Turtle shirt2',
            slug: 'Save-Turtle-Shirt2',
            category: 'Shirts',
            image:'/images/t2.jpg',
            price: 130,
            countInStock: 0,
            brand: 'Adidas',
            rating: 4.3,
            numReviews: 10,
            description: 'high Quality T-shirt with the theme of Save Turtle',
        },
        {
            //_id: '3',
            name: 'Green Turtle Toy',
            slug: 'green-turtle-toy',
            category: 'Toys',
            image:'/images/t1.png',
            price: 100,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Huggable Green Turtle Toy',
        },
        {   
            //_id: '4',
            name: 'Save Turtle Bracelet2',
            slug: 'Save-Turtle-Bracelet2',
            category: 'Bracelets',
            image:'/images/b1.png',
            price: 110,
            countInStock: 15,
            brand: 'Adidas',
            rating: 4.3,
            numReviews: 10,
            description: 'Stylish Bracelet with the theme of Save Turtle',
        },
    ],
  };
  export default data;